# Generated by Django 3.0.1 on 2020-01-27 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
        ('hotelroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroom',
            name='rhotel',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.Hotel'),
        ),
    ]
